### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mavsan** [jelmerdemaat/postcss-base64#2]
Error: ENOENT: no such file or directory, open 'H:\img\sprite.png'.

In css: /img/sprite.png.

Path to sprite.png: H:\OpenServer\domains\site\www\img\sprite.png

Path to gulpfile.js: H:\OpenServer\domains\site\www\gulpfile.js

**Comment by jelmerdemaat** [comment]
For anyone viewing this now, the path to the image was wrong. Make sure you pass the right paths.
