### ISSUE TITLE
doesn't resolve relative urls (e.g. //fonts.google.com/some-font.ttf)

### ISSUE THREAD

**Issue by niftylettuce** [jelmerdemaat/postcss-base64#8]
it requires https or http prefix - can we make it also work for relative url?

**Comment by jelmerdemaat** [comment]
Hi! Thanks for mentioning this! What this plugin does now is encode local files. It can't lookup files that are online / on a server. This is possible to make of course, but I doubt there are many use cases.

Although this plugin makes it possible, I would strongly advise **against** base64 encoding resources inside your CSS if you have other options. For fonts there are [better font loading strategies](https://www.zachleat.com/web/comprehensive-webfonts/). For icons there are [better ways to include svg's](https://cloudfour.com/thinks/our-svg-icon-process/). This counts even more for external resources, which could e.g. be be preloaded or loaded in parallel with http/2 in stead of hardcoding them into a CSS file.

Maybe you can make it more clear why you would want this inside this plugin.

Will mark it as an enhancement/question.
